# Portas do Servidor
server.port=8081

# Conexão CloudAMQP (Dados extraídos da sua URL)
spring.rabbitmq.host=fuji.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=omlpscph
spring.rabbitmq.password=1mbnpsy_DhYE1KnE5uHzcgxPxdhS7yDb
spring.rabbitmq.virtual-host=omlpscph

# Importante: Como a URL usa 'amqps', o SSL deve estar ativo
spring.rabbitmq.ssl.enabled=true

# Configurações de Negócio para o BDMG
bdmg.queue.name=proposta.analise.queue
bdmg.exchange.name=bdmg.analise.exchange
bdmg.routing.key=proposta.solicitada.key

# Banco de Dados H2 (Necessário para o projeto subir com JPA)
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Encoding para evitar erros no Maven
project.build.sourceEncoding=UTF-8